module.exports = [
  'What talent do you have that everyone doesn’t know about?',
  'What was the most indulgent item that you bought this year?',
  'What are your pet peeves?',
  'What is a memorable scene from a movie that you love?',
  'What are you really terrible at?',
  'What are you really good at?',
  'If you could change the world in one way, what would you change?',
  'What is the best part of your day?',
  'What was your favorite vacation and why?',
  'What do you love to eat now that you also enjoyed as a kid?',
  'What was the most beautiful place that you have ever visited and why?',
  'What is your favorite type of art? Abstract, realist, sculpture, etc.',
  'When was the last time you went to a museum?',
  'If you were an animal, which one would you be and why?',
  'So, how many people message you that just say “hi?”',
  'If you could wake up tomorrow with one super power, what would it be?',
  'If you could pick a new first name, what would it be?',
  'What’s your greatest fear ?',
  'If you had to be stranded on an island, what three things would you bring with you?',
  'If you could spend a night in a house that was haunted, would you?',
  'Who do you think you might have been in a past life?',
  'What’s the funniest thing that’s ever happened to you?',
  'Do you believe in ghosts?',
  'Would you like to survive an apocalypse? Why or why not?',
  'What’s the worst advice you’ve ever been given?',
  'What is your funniest talent?',
  'What is your favorite smell?',
  'What’s your funniest moment in life?',
  'When were you most embarrassed?',
  'What’s the weirdest thing you’ve ever dreamed?',
  'Have you ever sent a text to the wrong person?',
  'Dream job if money didn’t matter?',
  'What would you tell yourself five years ago?',
  'What is one thing that makes you unique?',
  'What are two of the things you are proud of in life?',
  'What are the top 3 movies you’ve watched?',
  'Do you have any pets?',
  'What have you always wanted to become?',
  'Who is your best author?',
  'What genre of movies do you enjoy watching?',
  'What are you thinking about now?',
  'Wanna go for an adventure together?',
  'Do you want to know a secret?'
];
